"use client";

import Head from "next/head";
import { BsCloudMoonFill, BsDiscord } from "react-icons/bs";
import {
  AiFillFacebook,
  AiFillInstagram,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
// import { BsFillMoonStarsFill } from "react-icons/bs";

import { useState } from "react";

import main from "../public/main.jpg";

import Image from "next/image";
import wildlife from "../public/wildlife.jpg";
import aunim from "../public/aunim.jpg";

import wedding from "../public/wedding.jpg";

import travelling from "../public/travelling.jpg";
import kuakata from "../public/kuakata.jpg";
import nature from "../public/nature.jpg";
import travelmanager from "../public/travelmanager.jpg";

import { Assistant } from "next/font/google";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Aunim-portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-black md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyabir</h1>
            <ul className="flex items-center">
              <li>
                <BsCloudMoonFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-black text- to-black text-white px-4 py-2 border-none rounded-md ml-8 ring-2 ring-orange-700 pointer-events-auto "
                  href="https://www.linkedin.com/in/mohd-mahdiuzzaman-aunim-838109139/"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-blue-700 font-medium dark:text-orange-700 md:text-6xl">
              Mahdiuzzaman Aunim
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Content Creator & Wildlife Photographer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for shoot and design content needs.
              Join me down below and lets get exploring!
            </p>
            <div
              className=" cursor-pointer
            text-5xl flex justify-center gap-3 py-3 text-gray-600 dark:text-gray-400"
            >
              <AiFillFacebook
                className="cursor-pointer transition duration-300 transform hover:scale-110"
                onClick={() => {
                  window.open(
                    "https://www.facebook.com/mahdiuzzamanaunim",
                    "_blank"
                  );
                }}
              />
              <AiFillInstagram
                className="cursor-pointer transition duration-300 transform hover:scale-110"
                onClick={() => {
                  window.open(
                    "https://www.instagram.com/mahdiuzzaman_aunim/",
                    "_blank"
                  );
                }}
              />
              <AiFillLinkedin
                className="cursor-pointer transition duration-300 transform hover:scale-110"
                onClick={() => {
                  window.open(
                    "https://www.linkedin.com/in/mohd-mahdiuzzaman-aunim-838109139",
                    "_blank"
                  );
                }}
              />
              <AiFillYoutube className="cursor-pointer transition duration-300 transform hover:scale-110" />
            </div>

            <div className=" mx-auto rounded-full w-80 h-80 relative overflow-hidden mt-10 md:h-96 md:w-96 cursor-pointer transition duration-300 transform hover:scale-110  ">
              <Image
                src={darkMode ? main : aunim}
                layout="fill"
                objectFit="cover"
                alt="boss"
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance photographer and
              editor, Ive done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              media buying and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 justify-center cursor-pointer transition duration-300 transform hover:scale-110">
              <Image
                className="rounded-lg mix-blend-luminosity min-h-center  "
                src={wedding}
                // width={100}
                // height={100}
                alt="adada"
              />
              <h3 className="text-lg font-medium pt-8 pb-2  ">Wedding Snaps</h3>
              <p className="py-2">
                Capturing raw and elegant moments of your dream life.
              </p>
              <h4 className="py-4 text-teal-600">contactme@01521255550</h4>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 cursor-pointer transition duration-300 transform hover:scale-110 ">
              <Image
                className="rounded-lg  container 
                "
                src={travelmanager}
                // width={100}
                // height={100}
                alt="ahdad"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Rank Boosting</h3>
              <p className="py-2">
                Do you have an itention for level up your gaming skills? Lets
                make it a reality.
              </p>
              <h3 className="py-4 text-teal-600">IGN: tdxaunimo_saw</h3>
              {/* <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p> */}
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 cursor-pointer transition duration-300 transform hover:scale-110">
              <Image
                className="container rounded-lg"
                src={travelling}
                // width={100} height={100}
                alt="adada"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover cursor-pointer transition duration-300 transform hover:scale-110 focus:ring-2 focus:ring-blue-500"
                // width={"100%"}
                // height={"100%"}
                layout="responsive"
                src={wildlife}
                alt="adda"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover cursor-pointer transition duration-300 transform hover:scale-110"
                // width={"100%"}
                // height={"100%"}
                layout="responsive"
                src={aunim}
                alt="self pot"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover cursor-pointer transition duration-300 transform hover:scale-110"
                // width={"100%"}
                // height={"100%"}
                layout="responsive"
                src={nature}
                alt="dadad"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover cursor-pointer transition duration-300 transform hover:scale-110"
                // width={"100%"}
                // height={"100%"}
                layout="responsive"
                src={kuakata}
                alt="happy couple"
              />
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
